# Generated by Django 2.0.5 on 2018-06-26 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='club_members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=50)),
                ('Rollno', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='clubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.CharField(default='', max_length=20)),
                ('club_name', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='ie_resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Rollno', models.CharField(max_length=10)),
                ('Phoneno', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('question1', models.TextField()),
                ('question2', models.TextField()),
                ('question3', models.TextField()),
                ('question4', models.TextField()),
                ('question5', models.TextField()),
                ('question6', models.TextField()),
                ('question7', models.TextField()),
                ('question8', models.TextField()),
                ('question9', models.TextField()),
                ('question10', models.TextField()),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.clubs')),
            ],
        ),
        migrations.AddField(
            model_name='club_members',
            name='club_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.clubs'),
        ),
    ]
