# Generated by Django 2.0.5 on 2018-06-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ie_resume',
            name='question1',
        ),
        migrations.RemoveField(
            model_name='ie_resume',
            name='question10',
        ),
        migrations.RemoveField(
            model_name='ie_resume',
            name='question2',
        ),
        migrations.RemoveField(
            model_name='ie_resume',
            name='question3',
        ),
        migrations.RemoveField(
            model_name='ie_resume',
            name='question4',
        ),
        migrations.RemoveField(
            model_name='ie_resume',
            name='question5',
        ),
        migrations.RemoveField(
            model_name='ie_resume',
            name='question6',
        ),
        migrations.RemoveField(
            model_name='ie_resume',
            name='question7',
        ),
        migrations.RemoveField(
            model_name='ie_resume',
            name='question8',
        ),
        migrations.RemoveField(
            model_name='ie_resume',
            name='question9',
        ),
    ]
