# Generated by Django 2.0.5 on 2018-06-26 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_auto_20180626_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ie_resume',
            name='club_id',
        ),
        migrations.DeleteModel(
            name='ie_resume',
        ),
    ]
